# Generated by Django 4.0.5 on 2022-08-22 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.TextField(max_length=500)),
            ],
            options={
                'db_table': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.TextField(max_length=64)),
                ('city_code', models.TextField(default='', max_length=3)),
            ],
            options={
                'db_table': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=500)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('domain_name', models.TextField(max_length=250)),
            ],
            options={
                'db_table': 'Domains',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(max_length=250)),
                ('last_name', models.TextField(max_length=250)),
                ('phone', models.TextField(max_length=14)),
                ('email', models.TextField(max_length=250)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.city')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.answer')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.user')),
            ],
            options={
                'db_table': 'UsersAnswers',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(max_length=500)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.domain')),
            ],
            options={
                'db_table': 'Questions',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.domain'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.user'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.question'),
        ),
    ]
