# Generated by Django 4.1 on 2022-08-28 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_alter_comment_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='apiapp.question'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.domain'),
        ),
    ]
